# Generated by Django 3.0.5 on 2020-04-10 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='starting time')),
                ('end_time', models.DateTimeField(verbose_name='ending time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.User')),
            ],
        ),
    ]
